version: "3.7"

services:
    web:
        build: ./docker/php-fpm
        container_name: web
        depends_on:
            - mysql
        volumes:
            - .:/var/www
    apache:
        build: ./docker/apache
        container_name: apache
        depends_on:
            - web
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
    mysql:
        image: mysql
        container_name: mysql
        ports:
            - "3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=true
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
