version: "3.7"

services:
    web:
        build: ./docker/centos
        container_name: web
        depends_on:
            - mysql
        ports:
            - "8000:80"
        volumes:
            - ./docker/centos/logs:/var/log/httpd
            - .:/var/www/html
    mysql:
        image: mysql
        container_name: mysql
        ports:
            - "3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=true
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
